var cText = '';
cText += '<div data-role="footer" data-position="fixed" data-id="samefooter">';
cText +=    '<div data-role="navbar">';
cText +=        '<ul>';
cText +=            '<li><a href="menu.html" data-icon="home" data-ajax="false">Menu</a></li>';
cText +=            '<li><a href="index.html" data-icon="plus" data-ajax="false">Today</a> </li>';
cText +=            '<li><a href="settings.html" data-icon="gear" data-ajax="false">Settings</a></li>';
cText +=        '</ul>';
cText +=    '</div>';
cText += '</div>';
document.write(cText);