var cText = '';
cText += '<div data-role="footer" data-position="fixed">';
cText +=    '<div data-role="navbar">';
cText +=        '<ul>';
cText +=            '<li><a href="../index.html" data-icon="home" data-ajax="false">Overview</a></li>';
cText +=            '<li><a href="add_hours.html" data-icon="plus" data-ajax="false">Add hours</a> </li>';
cText +=            '<li><a href="../Pages/settings.html" data-icon="gear" data-ajax="false">Settings</a></li>';
cText +=        '</ul>';
cText +=    '</div>';
cText += '</div>';
document.write(cText);